services:
  nginx:
    image: nginx:1.28.0
    restart: unless-stopped
    depends_on:
      - SERVOCE_NAME
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certs:/etc/nginx/certs